### ISSUE TITLE
PCF file error trying to access IO_32, IO_33 and IO_43 (SFBIO IOs)

### ISSUE THREAD

**Issue by timsaxe** [QuickLogic-Corp/quicklogic-fpga-toolchain#17]
I get the following message:
PCF constraint "set_io blueled		22" from line 4 constraints net blueled of a block type PB-BIDIR to a location for block types:
PB-SDIOMUX

The test example is located at qorc-sdk/qf_apps/qf_helloworldhw/fpga/rtl

It works when blueled is assigned to 38 (which is really the blueled) but if the PCF is changed to point to 22 then it fails.  The test PCF is:

set_io redled		34
set_io greenled		39
//set_io blueled		38
set_io blueled		22

I haven't done an exhaustive test, but I suspect that any IO 32 or greater will have the same issue.

**Comment by mkurc-ant** [comment]
I've fixed the issue with https://github.com/QuickLogic-Corp/symbiflow-arch-defs/pull/137. Basically the PCF file and PART type were not passed to the Yosys wrapper script. This caused the plugin that converts cells for SDIOMUX not being run.
