### ISSUE TITLE
conda activate breaks tinyfpagprogrammer

### ISSUE THREAD

**Issue by timsaxe** [QuickLogic-Corp/quicklogic-fpga-toolchain#24]
When I conda activate for symbiflow, tinyfpagprogrammer fails because the serial module is not available.  Please include serial in the symbiflow conda env and ensure that tinyfpgaprogrammer works.  It is cumbersome to have to conda active/deactivate between make a programming.

**Comment by kkumar23** [comment]
@timsaxe : Sure Tim, please provide details on adding serial module.

**Comment by timsaxe** [comment]
The way I did this was to ‘conda active’  then ‘pip3 install serial’

I believe our installer installs a bunch of modules, so I think the solution is to add serial to that list.  I have no idea how to do that.

**Comment by kkumar23** [comment]
Thanks @timsaxe , i will take care of this.

**Comment by kkumar23** [comment]
Fixed in Symbiflow v1.3.0
