### ISSUE TITLE
Failed to 'compile from source code'

### ISSUE THREAD

**Issue by jzhang-quicklogic** [QuickLogic-Corp/quicklogic-fpga-toolchain#32]
Trying to install Symbiflow by following '2) Compile from source code and run example'
I checked out the *yosos* repo already:
_git clone https://github.com/QuickLogic-Corp/yosys.git -b quicklogic-rebased quicklogic-yosys_
And ran the following commands:
_cd quicklogic-yosys
make config-gcc_

Then I got error below:
[Makefile.conf] CONFIG := gcc
/bin/sh: 1: pkg-config: not found
/bin/sh: 1: pkg-config: not found
bash: tclsh: command not found
/bin/sh: 1: pkg-config: not found
bash: tclsh: command not found
/bin/sh: 1: pkg-config: not found
/bin/sh: 1: gcc: not found

What is needed before compiling the source code? I suppose all the steps needed to complete Symbiflow installation should be there.

**Comment by kkumar23** [comment]
@jzhang-quicklogic : Each tool specific software requirements are listed on their repo. For eg yosys:
https://github.com/QuickLogic-Corp/yosys [Refer the Setup information on their read.md page]. Same for VTR as well.
