### ISSUE TITLE
Create account on hub.docker.com for Docker container images

### ISSUE THREAD

**Issue by Thirsty2** [QuickLogic-Corp/quicklogic-fpga-toolchain#40]
Publishing the images on Docker Hub allows pulling them without using longer (sometimes awkward) URLs.  If we publish an image named symbiflow-ql to Docker hub, anyone (or any machine building downstream docker images) can use simple URLs like:

docker run -it --rm -v $(pwd):/root/work symbiflow-ql:1.3.0 bash

or at the start of a Dockerfile:

FROM symbiflow-ql:1.3.0

It is possible to use URLs like this already, but only if a user has locally tagged an image as symbiflow-ql:1.3.0.  In order to use a prebuilt package from github, you need a longer and awkward url that is more difficult to remember, and you need to be authenticated as a github user.  The above become:

docker run -it -rm -v $(pwd):/root/work docker.pkg.github.com/quicklogic-corp/quicklogic-fpga-toolchain/symbiflow-ql:1.3.0 bash

and 

FROM docker.pkg.github.com/quicklogic-corp/quicklogic-fpga-toolchain/symbiflow-ql:1.3.0

and these only work for users who are authenticated with github.

**Comment by kkumar23** [comment]
@Thirsty2 : right will create a separate account. Will plan for that. Is docker supported in RHEL ? I do not see docker install on RHEL.https://docs.docker.com/engine/install/ . On Ubuntu I could run.

**Comment by Thirsty2** [comment]
I believe Docker is supported on recent versions of RHEL.  I have not tried it personally.

Doug

**Comment by whatnick** [comment]
This can be easily done in GitHub actions with this pre-built one : https://github.com/marketplace/actions/build-docker-images-using-cache

Better still we can push to all registries.

**Comment by kkumar23** [comment]
We are not planning to publish docker images for now.
