### ISSUE TITLE
The symbiflow-ql:1.3.0 package was built with the 1.2.0 installer

### ISSUE THREAD

**Issue by Thirsty2** [QuickLogic-Corp/quicklogic-fpga-toolchain#41]
The Dockerfile contains a default tag, which was left at 1.2.0 when the quicklogic-fpga-toolchain was tagged to 1.3.0, which triggered a github package build resulting in a package tag of 1.3.0 but building a container image from the 1.2.0 installer.

Ideally, we would delete the 1.3.0 package, but only github support can do that for published public packages, because the assumption is that someone could be using it in a CI/CD process or other critical use case.  The owner of this repo will have to request removal of this mis-tagged docker container package by github support.

We need to create a new tag of the quicklogic-fpga-toolchain to trigger github actions to create a new tagged package, perhaps something like 1.3.0.0.  The current release was tagged before changing the Dockerfile to use the 1.3.0 installer.  It also contains permissions that only allow the root user to run the tools.  If we create a new tag, the package will be re-built with the current Dockerfile that uses the 1.3.0 installer, and changes the permissions to 755 so anyone can run the symbiflow-ql tools.
 
https://github.com/QuickLogic-Corp/quicklogic-fpga-toolchain/packages/449834

We should change the github action build to automatically inject the --build-arg TAG to match the current tag during the package build so we don't need to change the default in the Dockerfile.  Perhaps a non-working default tag like v0.0.0 as suggested by coolbreeze413 is a good idea, as it would only build if someone injects a proper tag or manually tweaks the default on their machine.  Perhaps this deserves its own separate issue entry.  We may want to decouple the installer tag from the tag we give the image.  Creating a new 1.3.0.0 tag would trigger a build right now using the default installer of v1.3.0 which would work fine, but if we instead looked for a v1.3.0.0 installer, it would have to exist and be downloadable.  Going forward, this may not be an issue if the tag always matches the installer version.

**Comment by Thirsty2** [comment]
The following pull request should prevent this issue going forward.
https://github.com/QuickLogic-Corp/quicklogic-fpga-toolchain/pull/42

After the pull request is merged, one way to fix the package is to delete the current tag with 
git push --delete origin tagName

Then re-create tag v1.3.0 and push it, which will trigger a rebuild of the package and update it with the version built from the 1.3.0 installer.

**Comment by kkumar23** [comment]
@Thirsty2 : have re-created the release tag 1.3.0

**Comment by Thirsty2** [comment]
I tested the docker container image packages, and they both work.  Thanks for re-publishing the 1.3.0 tag.
