### ISSUE TITLE
PCF using alias name failed

### ISSUE THREAD

**Issue by philquik** [QuickLogic-Corp/quicklogic-fpga-toolchain#48]
Using below in PCF file will failed. 
set_io UART0_SIN_i IO_2
set_io UART0_SOUT_o IO_3
set_io UART1_SIN_i IO_41
set_io UART1_SOUT_o IO_40
set_io gnd_o IO_10

Error as below
PCF constraint "set_io UART1_SIN_i IO_41" from line 3 constraints net UART1_SIN_i of a block type PB-BIDIR to a location for block types:
PB-SDIOMUX

Change alias to IO location will fix the issue, but before make, needs to make clean, otherwise, it will still failed.

**Comment by kkumar23** [comment]
@philquik : I have corrected the script, please verify if there is any change in pcf file, the synthesis runs again. No need to make clean.  For the IO issue there is a ticket filed : https://github.com/QuickLogic-Corp/quicklogic-fpga-toolchain/issues/23
